# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-438232-marco/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/ip/clk_wiz_test {
      /home/marco/entwicklung/programme/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/marco/entwicklung/programme/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/ip/clk_wiz_test {
      ./.Xil/Vivado-438232-marco/realtime/blk_mem_gen_0_stub.v
      ./.Xil/Vivado-438232-marco/realtime/clk_wiz_test_stub.v
    }
      rt::read_vhdl -lib work {
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/uart/uart_tx_controller.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/uart/debounce.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/uart/uart_transmitter.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/uart/uart.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/uart/uart_mirror.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/uart/uart_rx_controller.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/top.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/sseg/sseg_controller.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/sseg/hexdecoder.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/sseg/sseg_cs_generator.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/protocols/i2c_master.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/vga/vga_template.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/vga/graphics_controller.vhd
      /home/marco/entwicklung/projekte/ArtyA7-Projects/nonprojectmode/src/vga/vga_controller.vhd
    }
      rt::read_vhdl -lib xpm /home/marco/entwicklung/programme/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-438232-marco/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-438232-marco/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-438232-marco/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
